version: "3"
services:
  scr:
    container_name: scr
    hostname: scr
    image: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ~/.MySQLDBData/mysqlonly/scr:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1756
      MYSQL_DATABASE: scr
      MYSQL_USER: scr
      MYSQL_PASSWORD: scr123globo
      TZ: America/Sao_Paulo
